### PR TITLE
fix: set maximum job timeout

### LINKED ISSUE #243: set a maximum time a job can take before marking it as failed
Sometimes some jobs may take a very long time when ran, causing the entire API queue to be stuck. We should set a maximum job time that helps in these edge cases and marks these jobs as failed.

### PR DESCRIPTION
**Pull request by rafaelcr**
Sets and enforces a maximum execution time for individual jobs.
Fixes #243

### CODE REVIEW

File: src/token-processor/queue/job/job.ts [hunk 1]
```diff
@@ -43,8 +43,13 @@ export abstract class Job {
     // what to do in each case. If we choose to retry, this queue entry will simply not be marked as
     // `processed = true` so it can be picked up by the queue at a later time.
     try {
-      await this.handler();
-      status = DbJobStatus.done;
+      const success = await resolveOrTimeout(this.handler(), ENV.JOB_QUEUE_TIMEOUT_MS);
```
Comment (zone117x) [inline src/token-processor/queue/job/job.ts:46]: When this times out and returns continues with `success==false`, what happens to the underlying promise? It doesn't look like there's termination code?

Comment (rafaelcr) [reply src/token-processor/queue/job/job.ts:46]: That part is supposed to be handled by the tookit here: https://github.com/hirosystems/api-toolkit/blob/develop/src/helpers/time.ts#L68
But let me know if you think I should add something extra like an abort controller, etc.

Comment (zone117x) [reply src/token-processor/queue/job/job.ts:46]: Here's the scenario that seems like it could cause issues:
```js
async function someTask() {
  await sleep(10_000);
  console.log('something happens because task was still going');
}
const success = await resolveOrTimeout(someTask(), 100);
console.log(`Task done, success: ${success}`);
```

In something like the above, you'd hit the `task done`, then later on have a dangling side-effect triggered in the background

**Review by zone117x — APPROVED** [review]
